version: "3.6"
services:
  app:
    build:
      .
    container_name: rss_reader
    stdin_open: true
    tty: true
    environment:
      MONGO_HOST: mongo
    volumes:
      - type: bind
        source: ./app/saved_files
        target: /code/app/saved_files
        consistency: delegated
  mongo:
    image: mongo
    ports:
      - "27017:27017"
